"""Phase 5-1 시드 - 72 task (12 기존 + 60 신규) × 6 paraphrase + 90 noise.

신규 60 task 는 round 16 dogfooding (`tuna_general_task` glm-4.7) 결과 차용.
기존 12 task 는 Phase 4-3 시드 (test_search_quality_extended.py) 와 동일.
"""

from __future__ import annotations

# 기존 Phase 4-3 시드 (12 task × 6 paraphrase = 72 record).
ORIGINAL_GROUPS: list[list[str]] = [
    ["메모리 누수 탐지", "memory leak detection", "할당 해제 안 된 객체 찾기",
     "GC 가 안 돌아가는 문제", "garbage collection 디버깅", "OOM 발생 추적"],
    ["이메일 검증 로직", "validate email format", "메일 주소 유효성 체크",
     "RFC 5322 준수 검사", "정규식으로 메일 거름", "email format check function"],
    ["파일 압축", "compress file size", "용량 줄이기",
     "gzip 적용", "데이터 사이즈 다이어트", "binary 작게 만들기"],
    ["JSON 파싱 함수", "parse JSON safely", "JSON 디코딩 처리",
     "json.loads 호출", "역직렬화 구현", "deserialize JSON document"],
    ["비밀번호 해시", "password hashing with bcrypt", "credential 단방향 암호화",
     "단방향 hash 함수", "salt 추가한 hash", "credential one-way hashing"],
    ["API rate limit 구현", "요청 빈도 제한", "throttling 미들웨어",
     "토큰 버킷 알고리즘", "초당 호출 제한", "leaky bucket implementation"],
    ["logging 구조 설계", "log 출력 포맷", "구조화 로그",
     "structured logging with loguru", "loguru 사용", "로그 포맷 지정"],
    ["캐싱 전략", "메모리 캐시 구현", "LRU cache",
     "Redis 캐시 적용", "캐시 무효화", "cache TTL 설정"],
    ["비동기 처리", "async/await 사용", "동시성 코드",
     "코루틴 작성", "asyncio event loop", "non-blocking I/O"],
    ["DB 마이그레이션", "schema 변경 스크립트", "Alembic 사용",
     "다운타임 없는 마이그레이션", "rollback 전략", "컬럼 추가 migration"],
    ["직렬화 처리", "객체 → JSON dump", "pickle 사용",
     "msgpack 직렬화", "역직렬화 deserialize", "binary serialization"],
    ["정렬 알고리즘", "quicksort 구현", "merge sort",
     "안정 정렬", "부분 정렬", "in-place sort"],
]

# 신규 60 task (round 16 dogfooding 차용).
NEW_GROUPS_60: list[list[str]] = [
    # system_programming (10)
    ["file I/O 처리", "open file for writing", "파일 디스크립터 다루기",
     "fopen/fclose 패턴", "context manager 로 파일 열기", "binary file write"],
    ["시그널 핸들링 구현", "handle SIGINT/SIGTERM", "시그널 인터럽트 처리",
     "signal handler registration", "비동기 신호 제어", "catch system signals"],
    ["프로세스 포크 구현", "forking a child process", "자식 프로세스 생성",
     "create new process via fork", "프로세스 분기 처리", "process duplication"],
    ["데몬 프로세스 생성", "create a background daemon", "백그라운드 서비스 구현",
     "daemonize a process", "데몬화 작업", "detach from terminal"],
    ["공유 메모리 설정", "shared memory allocation", "프로세스 간 메모리 공유",
     "shmget/shmat usage", "IPC shared memory", "inter-process memory map"],
    ["sysctl 파라미터 튜닝", "modify kernel parameters via sysctl",
     "시스템 커널 설정 변경", "tune sysctl values", "커널 런타임 설정",
     "sysctl configuration"],
    ["proc 파일시스템 분석", "read /proc filesystem", "프로세스 정보 추출",
     "parsing /proc entries", "커널 상태 확인", "procfs data extraction"],
    ["시스템 콜 트레이싱", "trace system calls", "strace 도구 활용",
     "syscall monitoring", "커널 진입점 추적", "intercepting syscalls"],
    ["OOM 킬러 튜닝", "out-of-memory killer tuning", "OOM score 조정",
     "prevent OOM kill", "메모리 부족 시 프로세스 보호", "oom_adj configuration"],
    ["커널 모듈 로드", "load kernel module", "LKM 구현",
     "insmod/rmmod usage", "커널 드라이버 삽입", "kernel module development"],
    # network (10)
    ["HTTP 클라이언트 구현", "build an HTTP client", "웹 요청 라이브러리 작성",
     "send HTTP requests", "HTTP 통신 모듈", "request-response cycle"],
    ["웹소켓 서버 구축", "websocket server implementation", "실시간 양방향 통신",
     "websocket handshake", "소켓 기반 실시간 전송", "full-duplex communication"],
    ["gRPC 서비스 정의", "implement gRPC service", "Protocol Buffers 정의",
     "gRPC remote procedure call", "IDL 기반 통신", "grpc server/client setup"],
    ["재시도 및 백오프 전략", "retry with exponential backoff", "재시도 로직 구현",
     "backoff algorithm", "지수적 백오프 적용", "retry mechanism"],
    ["커넥션 풀 관리", "connection pool implementation", "DB 연결 풀링",
     "manage connection reuse", "커넥션 재사용 로직", "pooling database connections"],
    ["TLS 핸드셰이크 처리", "TLS handshake process", "암호화 연결 설정",
     "secure socket layer setup", "TLS 인증 과정", "establish encrypted session"],
    ["DNS 룩업 구현", "DNS lookup resolution", "도메인 이름 해석",
     "resolve hostname to IP", "DNS 쿼리 처리", "domain name system query"],
    ["프록시 서버 구축", "build a proxy server", "중계 서버 구현",
     "forwarding network requests", "리버스 프록시 설정", "proxying traffic"],
    ["서킷 브레이커 패턴", "circuit breaker implementation", "장애 전파 방지",
     "fail-fast mechanism", "서비스 차단 로직", "circuit breaker state machine"],
    ["속도 제한 폴링", "rate-limited polling", "API 호출 제한 처리",
     "throttling poll requests", "폴링 주기 제어", "rate limiting logic"],
    # data_structures (10)
    ["트라이 구조 구현", "trie data structure", "접두사 트리 작성",
     "prefix tree implementation", "문자열 검색 트리", "trie insert/search"],
    ["힙 자료구조 구현", "binary heap implementation", "우선순위 큐 구축",
     "max/min heap logic", "힙 정렬 알고리즘", "priority queue heap"],
    ["연결 리스트 작성", "linked list implementation", "노드 기반 리스트",
     "singly/doubly linked list", "포인터 연결 리스트", "list node manipulation"],
    ["스키프 리스트 구현", "skip list implementation", "계층형 연결 리스트",
     "fast search skip list", "확률적 검색 구조", "skip list indexing"],
    ["B-트리 구현", "B-tree implementation", "균형 검색 트리",
     "disk-friendly tree", "B-tree node splitting", "multi-way search tree"],
    ["블룸 필터 구현", "bloom filter implementation", "확률적 집합 확인",
     "membership test filter", "해시 기반 필터", "bloom filter false positives"],
    ["LRU 맵 구현", "LRU cache map", "최근 최소 사용 제거",
     "least recently used map", "캐시 교체 알고리즘", "LRU eviction policy"],
    ["서로소 집합 구현", "disjoint set union", "Union-Find 알고리즘",
     "disjoint set forest", "집합 합치기 및 찾기", "DSU implementation"],
    ["접미사 배열 작성", "suffix array construction", "문자열 접미사 정렬",
     "suffix array build", "접미사 배열 검색", "suffix sorting"],
    ["세그먼트 트리 구현", "segment tree implementation", "구간 합 쿼리",
     "range query tree", "세그먼트 트리 업데이트", "interval tree logic"],
    # concurrency (10)
    ["뮤텍스 락 구현", "mutex lock implementation", "상호 배제 제어",
     "mutual exclusion", "임계 구역 보호", "locking mechanism"],
    ["세마포어 제어", "semaphore implementation", "리소스 카운팅 제어",
     "counting semaphore", "세마포어 대기/신호", "semaphore wait/signal"],
    ["비동기 큐 작성", "async queue implementation", "비동기 메시지 큐",
     "asynchronous producer-consumer", "async task queue", "non-blocking queue"],
    ["경쟁 상태 해결", "fix race condition", "데이터 경쟁 수정",
     "race condition prevention", "동기화 버그 수정", "thread safety fix"],
    ["스레드 풀 구현", "thread pool implementation", "작업자 스레드 관리",
     "worker thread pool", "스레드 재사용 로직", "managing thread pool"],
    ["워크 스틸링 알고리즘", "work stealing implementation", "부하 분산 스케줄링",
     "work stealing scheduler", "작업 훔치기 로직", "load balancing threads"],
    ["채널 통신 구현", "channel communication", "CSP 기반 메시징",
     "go-style channels", "채널을 통한 데이터 전송", "inter-thread channels"],
    ["퓨처/프로미스 구현", "future promise implementation", "비동기 결과 예약",
     "async result handle", "promise-based async", "future value retrieval"],
    ["데드락 탐지 로직", "deadlock detection", "교착 상태 탐지",
     "detecting circular wait", "deadlock prevention", "deadlock analysis"],
    ["원자적 CAS 구현", "atomic CAS operation", "Compare-And-Swap 구현",
     "lock-free atomic update", "CAS 기반 동기화", "atomic compare and swap"],
    # crypto_security (10)
    ["AES 암호화 구현", "AES encryption", "대칭키 암호화",
     "AES-GCM mode", "블록 암호화 처리", "symmetric key cipher"],
    ["RSA 서명 생성", "RSA digital signature", "공개키 서명 구현",
     "RSA sign and verify", "비대칭키 서명", "asymmetric signing"],
    ["JWT 검증 로직", "JWT verification", "JSON 웹 토큰 검증",
     "verify JWT signature", "토큰 유효성 확인", "JWT decode and validate"],
    ["OAuth2 플로우 구현", "OAuth2 authorization flow", "인증 코드 부여 방식",
     "OAuth2 grant type", "OAuth2 인증 절차", "access token exchange"],
    ["CSRF 토큰 처리", "CSRF token implementation", "사이트 간 요청 위조 방지",
     "CSRF protection", "anti-CSRF token", "cross-site request forgery fix"],
    ["비밀번호 재설정 로직", "password reset flow", "비밀번호 변경 절차",
     "secure password reset", "재설정 토큰 발행", "password recovery process"],
    ["키 로테이션 구현", "key rotation mechanism", "암호키 주기적 교체",
     "rotating encryption keys", "키 갱신 로직", "cryptographic key rotation"],
    ["mTLS 설정", "mTLS implementation", "상호 TLS 인증",
     "mutual TLS handshake", "양방향 인증서 검증", "mutual authentication TLS"],
    ["HMAC 생성 및 검증", "HMAC implementation", "해시 기반 메시지 인증",
     "generate HMAC signature", "HMAC-SHA256", "keyed-hash message authentication"],
    ["솔트 생성 로직", "salt generation for hashing", "비밀번호 솔팅",
     "cryptographic salt", "random salt creation", "password salting process"],
    # devops (10)
    ["docker compose 작성", "docker compose file", "멀티 컨테이너 설정",
     "docker-compose.yml", "컨테이너 오케스트레이션", "docker compose up"],
    ["k8s 배포 설정", "kubernetes deployment", "k8s 매니페스트 작성",
     "deploy to k8s", "쿠버네티스 배포 전략", "k8s deployment yaml"],
    ["terraform 모듈 구현", "terraform module creation", "IaC 인프라 정의",
     "terraform resource", "테라폼 모듈화", "infrastructure as code terraform"],
    ["helm 차트 작성", "helm chart implementation", "k8s 패키지 관리",
     "create helm chart", "헬름 템플릿 작성", "helm release management"],
    ["github actions 설정", "github actions workflow", "CI/CD 파이프라인 구축",
     "github actions yaml", "자동화 워크플로우", "github ci automation"],
    ["ansible 플레이북 작성", "ansible playbook creation", "구성 관리 자동화",
     "ansible role setup", "앤서블 설정 파일", "ansible automation"],
    ["prometheus 알람 설정", "prometheus alert rule", "모니터링 알람 정의",
     "prometheus alerting", "프로메테우스 경고 설정", "promql alert rules"],
    ["grafana 대시보드 구성", "grafana dashboard setup", "시각화 패널 작성",
     "grafana panel config", "그라파나 대시보드 설계", "monitoring dashboard grafana"],
    ["로그 집계 시스템", "log aggregation setup", "중앙 집중 로그 수집",
     "ELK stack implementation", "로그 수집 파이프라인", "centralized logging"],
    ["블루-그린 배포 구현", "blue-green deployment", "무중단 배포 전략",
     "blue-green switch", "배포 버전 전환", "zero-downtime deployment"],
]

# Noise 90: Phase 4-3 의 30 + round 16 의 60 (git 중복 일부 제거 / 다양화).
NOISE_90: list[str] = [
    # 기존 30 (Phase 4-3)
    "matplotlib 차트 그리기", "ANSI 컬러 출력", "argparse 사용법",
    "flask route 설정", "pygame window 생성", "pandas dataframe merge",
    "requests timeout 설정", "yaml 파일 파싱", "re 정규표현식 그룹",
    "tkinter 버튼 이벤트", "selenium headless 모드", "pytest fixture scope",
    "docker compose build", "kubernetes pod status", "git rebase interactive",
    "ssh key 생성", "vim mapping 설정", "bash script loop",
    "json path query", "xml parser setup", "sql join optimization",
    "redis pubsub", "rabbitmq exchange", "kafka consumer group",
    "grpc service definition", "protobuf field numbering", "aws s3 upload",
    "azure blob storage", "gcp cloud functions", "terraform state lock",
    # round 16 추가 60 - 다양화 (git 키워드는 1-2 개로 압축)
    "vim command mode", "jq filter query", "makefile target",
    "latex equation", "postgres explain analyze", "redis-cli monitor",
    "npm install", "pip freeze", "bash alias",
    "zsh rc config", "ssh-keygen", "grep recursive",
    "sed replace", "awk print", "chmod 755",
    "chown user", "curl verbose", "wget mirror",
    "dig mx record", "nslookup", "ping latency",
    "top process", "htop view", "df -h disk",
    "free -m memory", "uptime check", "ls -al",
    "mkdir -p", "rm -rf", "cp -r",
    "mv rename", "tar -xzvf", "zip -r",
    "unzip file", "gzip compress", "bzip2",
    "cron job", "systemctl restart", "journalctl -u",
    "dmesg", "tail -f", "cat file",
    "less viewer", "more pager", "head -n",
    "nano editor", "emacs keybind", "tmux session",
    "screen attach", "fzf search", "ripgrep rg",
    "vimdiff", "git stash apply", "git log --oneline",
    "pyproject.toml", "uv sync", "mise install",
    "rustup toolchain", "cargo build release", "go mod tidy",
    "mvn dependency tree", "gradle wrapper",
]

ALL_GROUPS = ORIGINAL_GROUPS + NEW_GROUPS_60  # 12 + 60 = 72 task
TOTAL_RECORDS = sum(len(g) for g in ALL_GROUPS) + len(NOISE_90)  # 72*6 + 90 = 522
