"""Phase 5-E (C) 시드 - 132 task × 6 paraphrase + 192 noise = 984 record.

기존 72 task (extended_500.py 의 ORIGINAL_GROUPS + NEW_GROUPS_60) +
신규 60 task (Round 19 dogfooding, mobile / web / backend / ml /
observability / data pipeline) + noise 92+100 = 192.
"""

from __future__ import annotations

from .extended_500 import ALL_GROUPS as _GROUPS_72
from .extended_500 import NOISE_90

# Round 19 dogfooding 차용 - 60 task × 6 paraphrase (mobile / web / backend /
# ml / observability / data_pipeline 각 10 task).
NEW_GROUPS_60_v2: list[list[str]] = [
    # mobile_dev (10)
    ["SwiftUI 화면 전환 구현", "implement SwiftUI navigation stack",
     "SwiftUI 내비게이션 구조 잡는 법", "How to handle navigation in SwiftUI",
     "SwiftUI 뷰 전환 로직 작성", "SwiftUI navigation view implementation"],
    ["Android Room 마이그레이션", "Android Room database migration guide",
     "Room DB 버전 업데이트 방법", "How to migrate Room database schema",
     "안드로이드 룸 마이그레이션 전략", "Room migration strategy for Android"],
    ["Flutter 상태 관리 선택", "Flutter state management options",
     "플러터 상태 관리 라이브러리 비교", "Which state management to use in Flutter",
     "Flutter 상태 관리 구현 방식", "Flutter state management best practices"],
    ["React Native 브릿지 설정", "React Native bridge configuration",
     "RN 네이티브 모듈 브릿지 연결", "How to create RN native bridge",
     "리액트 네이티브 브릿지 통신", "React Native bridge implementation"],
    ["Jetpack Compose 생명주기", "Jetpack Compose lifecycle management",
     "컴포즈 뷰 생명주기 처리", "Handling lifecycle in Jetpack Compose",
     "Compose LifecycleEvent 구현", "Jetpack Compose lifecycle hooks"],
    ["iOS 푸시 알림 설정", "iOS push notification setup",
     "아이폰 푸시 알림 구현 방법", "How to configure APNs for iOS",
     "iOS 푸시 메시지 수신 처리", "iOS push notification integration"],
    ["Android 백그라운드 작업", "Android background work processing",
     "안드로이드 백그라운드 서비스 구현", "How to run background tasks in Android",
     "WorkManager 활용 백그라운드 처리", "Android background job scheduling"],
    ["Flutter 플랫폼 채널", "Flutter platform channel usage",
     "플러터 네이티브 채널 통신", "How to use MethodChannel in Flutter",
     "Flutter 플랫폼 채널 구현", "Flutter platform channel communication"],
    ["RN 내비게이션 스택", "React Native navigation stack setup",
     "RN 스택 내비게이션 구조", "How to manage navigation stack in RN",
     "리액트 네이티브 화면 스택 관리", "RN navigation stack implementation"],
    ["모바일 키보드 핸들링", "Mobile keyboard handling techniques",
     "모바일 입력창 키보드 처리", "How to handle soft keyboard in mobile apps",
     "키보드 올라올 때 뷰 처리", "Mobile keyboard avoidance and handling"],
    # web_frontend (10)
    ["React hook 의존성 배열", "React hook dependency array",
     "리액트 훅 의존성 배열 최적화", "How dependency array works in useEffect",
     "React hook 의존성 관리", "React useEffect dependency array logic"],
    ["Vue composition API 활용", "Using Vue composition API",
     "뷰 컴포지션 API 구현 방법", "How to use setup function in Vue 3",
     "Vue composition API 전환", "Vue 3 composition API patterns"],
    ["Svelte 반응성 원리", "Svelte reactivity system",
     "스벨트 반응성 변수 선언", "How reactivity works in Svelte",
     "Svelte 상태 업데이트 메커니즘", "Svelte reactive declarations"],
    ["Next.js SSR 데이터 페칭", "Next.js SSR data fetching",
     "넥스트 서버사이드 렌더링 데이터 가져오기",
     "How to fetch data in Next.js getServerSideProps",
     "Next.js SSR 데이터 요청", "Next.js server-side data fetching"],
    ["React context 메모이제이션", "React context memoization",
     "리액트 컨텍스트 성능 최적화", "How to prevent re-renders in React context",
     "React context value memo", "Optimizing React context with useMemo"],
    ["Tailwind 다크모드 설정", "Tailwind CSS dark mode config",
     "테일윈드 다크모드 적용 방법", "How to implement dark mode in Tailwind",
     "Tailwind dark: 클래스 활용", "Tailwind CSS dark mode implementation"],
    ["CSS 그리드 레이아웃", "CSS grid layout design",
     "CSS 그리드 배치 방법", "How to use CSS Grid for layout",
     "CSS Grid 시스템 구현", "CSS grid layout patterns"],
    ["웹 접근성 ARIA 속성", "Web accessibility ARIA attributes",
     "웹 접근성 향상을 위한 ARIA 설정", "How to use ARIA roles for accessibility",
     "ARIA 속성 적용 가이드", "Web accessibility ARIA implementation"],
    ["폼 유효성 검사 구현", "Form validation implementation",
     "웹 폼 입력값 검증 방법", "How to handle form validation in web",
     "프론트엔드 폼 유효성 체크", "Client-side form validation"],
    ["인피니트 스크롤 구현", "Infinite scroll implementation",
     "무한 스크롤 리스트 구현", "How to build infinite scrolling in web",
     "Intersection Observer 기반 무한 스크롤", "Infinite scroll pagination logic"],
    # backend_api (10)
    ["API 버전 관리 전략", "API versioning strategies",
     "REST API 버전ing 방법", "How to manage API versions",
     "API 버전 경로 설계", "API versioning best practices"],
    ["GraphQL 리졸버 작성", "GraphQL resolver implementation",
     "그래프큐엘 리졸버 정의", "How to write GraphQL resolvers",
     "GraphQL 데이터 페칭 리졸버", "GraphQL resolver logic"],
    ["WebSocket 재연결 로직", "WebSocket reconnection logic",
     "웹소켓 끊김 처리 및 재연결", "How to implement WebSocket retry",
     "WebSocket heartbeat and reconnect", "WebSocket reconnection strategy"],
    ["페이지네이션 커서 방식", "Pagination cursor based approach",
     "커서 기반 페이지네이션 구현", "How to implement cursor pagination",
     "Cursor-based pagination logic", "API pagination using cursors"],
    ["사용자별 Rate Limit", "Rate limiting per user",
     "API 요청 횟수 제한 구현", "How to implement rate limiting",
     "User-based request throttling", "API rate limit implementation"],
    ["파일 업로드 스트리밍", "File upload streaming",
     "대용량 파일 업로드 스트림 처리", "How to stream file uploads in API",
     "Multipart file streaming", "API file upload streaming"],
    ["OpenAPI 스펙 정의", "OpenAPI specification definition",
     "Swagger OpenAPI 문서 작성", "How to define OpenAPI spec",
     "OpenAPI 3.0 설계", "OpenAPI specification guide"],
    ["응답 데이터 압축", "Response compression",
     "API 응답 gzip 압축 설정", "How to enable response compression",
     "HTTP response compression", "API response compression logic"],
    ["요청 데이터 검증", "Request validation",
     "API 입력값 검증 로직", "How to validate incoming requests",
     "Request payload validation", "API request validation patterns"],
    ["멱등성 키 구현", "Idempotency key implementation",
     "API 멱등성 보장 방법", "How to use idempotency keys in REST",
     "중복 요청 방지 멱등성 키", "Idempotency key logic for APIs"],
    # ml_inference (10)
    ["vLLM 배포 방법", "vLLM deployment guide",
     "vLLM 기반 LLM 서빙", "How to deploy models using vLLM",
     "vLLM 추론 서버 설정", "vLLM model serving implementation"],
    ["ONNX 모델 익스포트", "ONNX model export",
     "PyTorch 모델 ONNX 변환", "How to export model to ONNX",
     "ONNX 포맷 변환 방법", "ONNX export process"],
    ["GGUF 양자화 적용", "GGUF quantization",
     "LLM GGUF 양자화 방법", "How to quantize models to GGUF",
     "GGUF 포맷 양자화 설정", "GGUF quantization implementation"],
    ["배치 추론 최적화", "Batch inference optimization",
     "LLM 배치 처리 성능 향상", "How to implement batch inference",
     "추론 효율을 위한 배치 처리", "Batch inference strategy"],
    ["임베딩 캐시 구현", "Embedding cache implementation",
     "벡터 임베딩 캐싱 전략", "How to cache embeddings",
     "Embedding storage caching", "Embedding cache system"],
    ["모델 웜업 설정", "Model warmup configuration",
     "추론 서버 모델 웜업", "How to perform model warmup",
     "LLM warmup requests", "Model warmup strategy"],
    ["GPU 메모리 프로파일링", "GPU memory profiling",
     "GPU 메모리 사용량 분석", "How to profile GPU memory",
     "Nvidia-smi 기반 메모리 체크", "GPU memory profiling tools"],
    ["프롬프트 캐싱", "Prompt caching",
     "LLM 프롬프트 캐시 적용", "How to implement prompt caching",
     "KV 캐시 및 프롬프트 최적화", "Prompt caching mechanism"],
    ["스트리밍 응답 구현", "Streaming response implementation",
     "LLM 토큰 스트리밍 출력", "How to implement streaming LLM response",
     "Server-Sent Events 기반 스트리밍", "LLM streaming output"],
    ["함수 호출 구현", "Function calling implementation",
     "LLM Tool use 구현", "How to implement function calling in LLM",
     "LLM 함수 호출 인터페이스", "Function calling logic"],
    # observability (10)
    ["구조화된 로깅", "Structured logging",
     "JSON 기반 구조화 로깅", "How to implement structured logging",
     "로그 포맷 구조화 방법", "Structured logging patterns"],
    ["OpenTelemetry 트레이싱", "OpenTelemetry tracing",
     "분산 트레이싱 설정", "How to use OpenTelemetry for tracing",
     "OTel 트레이스 구현", "OpenTelemetry tracing setup"],
    ["Prometheus 익스포터", "Prometheus exporter",
     "프로메테우스 메트릭 수집", "How to create Prometheus exporter",
     "Custom Prometheus metrics", "Prometheus exporter implementation"],
    ["Grafana 알람 설정", "Grafana alert configuration",
     "그라파나 알림 규칙 생성", "How to set up Grafana alerts",
     "Grafana alerting rules", "Grafana alert implementation"],
    ["분산 트레이스 컨텍스트", "Distributed trace context",
     "트레이스 ID 전파 방법", "How to propagate trace context",
     "Distributed tracing context", "Trace context propagation"],
    ["로그 샘플링 전략", "Log sampling strategy",
     "로그 데이터 샘플링 방법", "How to implement log sampling",
     "로그 양 조절 샘플링", "Log sampling implementation"],
    ["에러 버짓 SLO", "Error budget SLO",
     "SLO 기반 에러 버짓 설정", "How to define error budget for SLO",
     "SRE 에러 버짓 관리", "Error budget SLO implementation"],
    ["스팬 속성 정의", "Span attribute definition",
     "트레이싱 스팬 속성 추가", "How to add attributes to spans",
     "OTel span attributes", "Span attribute configuration"],
    ["메트릭 카디널리티", "Metric cardinality",
     "메트릭 카디널리티 최적화", "How to handle high cardinality metrics",
     "Prometheus 카디널리티 문제", "Metric cardinality management"],
    ["로그 보관 정책", "Log retention policy",
     "로그 보관 주기 설정", "How to define log retention policy",
     "로그 아카이빙 및 삭제 정책", "Log retention implementation"],
    # data_pipeline (10)
    ["Airflow DAG 작성", "Airflow DAG implementation",
     "에어플로우 파이프라인 정의", "How to write Airflow DAGs",
     "Airflow 워크플로우 설계", "Airflow DAG configuration"],
    ["Spark 파티셔닝", "Spark partitioning",
     "스파크 데이터 파티셔닝 최적화", "How to partition data in Spark",
     "Spark partition tuning", "Spark partitioning strategy"],
    ["Kafka Exactly-once", "Kafka exactly-once semantics",
     "카프카 정확히 한 번 처리", "How to implement exactly-once in Kafka",
     "Kafka EOS 설정", "Kafka exactly-once implementation"],
    ["dbt 모델 정의", "dbt model definition",
     "dbt를 이용한 데이터 변환", "How to create dbt models",
     "dbt SQL 모델 작성", "dbt model implementation"],
    ["Parquet 스키마 진화", "Parquet schema evolution",
     "파케이 스키마 변경 처리", "How to handle Parquet schema evolution",
     "Parquet 파일 스키마 업데이트", "Parquet schema evolution strategy"],
    ["S3 멀티파트 업로드", "S3 multipart upload",
     "S3 대용량 파일 분할 업로드", "How to use S3 multipart upload",
     "S3 multipart upload API", "S3 multipart upload implementation"],
    ["CDC 구현 방법", "Change Data Capture implementation",
     "데이터 변경분 캡처 구현", "How to implement CDC",
     "Debezium 기반 CDC 설정", "CDC pipeline implementation"],
    ["Dead Letter Queue", "Dead Letter Queue implementation",
     "메시지 처리 실패 큐 설정", "How to implement DLQ in Kafka",
     "DLQ 기반 에러 처리", "Dead letter queue strategy"],
    ["백필 전략 수립", "Backfill strategy",
     "데이터 백필 처리 방법", "How to implement data backfill",
     "과거 데이터 재처리 전략", "Data backfill implementation"],
    ["데이터 품질 테스트", "Data quality testing",
     "데이터 파이프라인 품질 검증", "How to implement data quality tests",
     "Great Expectations 활용 검증", "Data quality test implementation"],
]

NOISE_100_v2: list[str] = [
    "vim macro recording", "emacs lisp configuration", "fish shell alias",
    "powershell script", "applescript automation", "gnu make file",
    "cmake build system", "bazel rules", "ninja build tool", "scons build",
    "vim plugin manager", "emacs theme", "zsh oh-my-zsh", "bashrc settings",
    "tmux session", "screen multiplexer", "grep regex", "sed stream editor",
    "awk processing", "find command",
    "ssh config", "scp transfer", "rsync backup", "chmod permissions",
    "chown ownership", "tar archive", "gzip compression", "curl request",
    "wget download", "dig dns lookup",
    "netstat port", "tcpdump packet", "wireshark capture", "nmap scan",
    "openssl cert", "gpg encryption", "ssh-keygen", "iptables firewall",
    "ufw setup", "fail2ban config",
    "docker image", "podman container", "kubernetes pod", "helm chart",
    "terraform state", "ansible playbook", "vagrant box", "virtualbox vm",
    "vmware workstation", "qemu emulator",
    "redis key", "memcached cache", "mongodb collection", "postgresql index",
    "mysql query", "sqlite db", "cassandra cluster", "elasticsearch index",
    "rabbitmq queue", "activemq broker",
    "http header", "https tls", "dns record", "tcp handshake", "udp packet",
    "icmp ping", "smtp mail", "ftp transfer", "ssh tunnel", "websocket frame",
    "python pip", "npm install", "yarn package", "maven pom", "gradle build",
    "cargo rust", "go mod", "ruby gem", "composer php", "pipenv virtualenv",
    "git commit", "git rebase", "git merge", "git stash", "svn checkout",
    "mercurial hg", "perforce helix", "bitbucket repo", "gitlab ci",
    "github action",
    "markdown syntax", "latex equation", "yaml format", "json schema",
    "xml parsing", "toml config", "ini file", "csv parsing",
    "protobuf definition", "avro schema",
]


ALL_GROUPS_132 = _GROUPS_72 + NEW_GROUPS_60_v2  # 72 + 60 = 132 task
NOISE_192 = NOISE_90 + NOISE_100_v2  # 92 + 100 = 192 (NOISE_90 가 실제 92개)
TOTAL_RECORDS_1K = sum(len(g) for g in ALL_GROUPS_132) + len(NOISE_192)
# 132 * 6 + 192 = 984 record
